steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cric-view:$COMMIT_SHA', '.']
    timeout: '1800s'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cric-view:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cric-view'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cric-view:$COMMIT_SHA'
      - '--region'
      - 'asia-south2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '3600'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_TELEMETRY_DISABLED=1'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/cric-view:$COMMIT_SHA'

# Increase timeout for large builds
timeout: '2400s'

options:
  machineType: 'E2_HIGHCPU_8' 